### ISSUE TITLE
New version available

### ISSUE THREAD

**Issue by Wakie87** [magenx/Interactive-Magento-2-Server-Installation#160]
https://github.com/magenx/Interactive-Magento-2-Server-Installation/blob/a8684db7946374df383845232142f46291f96600/Magento-2/CentOS-7/MASC-M-7-v2.sh#L1734

needs to be updated to the latest version:

"http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jre-8u181-linux-x64.rpm"

**Comment by magenx** [comment]
yes this will be updated,
thank you

**Comment by Wakie87** [comment]
needs to be updated to the latest version again.
